name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - jupyterlab
  - matplotlib
  - pandas
  - pyarrow
  - scikit-learn
  - xlrd
  - fbprophet
  - plotly
  - statsmodels
  - seaborn
  - bokeh
  - pyviz::panel
  - nodejs
  - hvplot
  - jupyter-panel-proxy
  - openpyxl
  - XlsxWriter
